# Ultrassonic
GPIO_PORT_IN_ULTR_ECHO = 7
GPIO_PORT_OUT_ULTR_TRIGG = 18

# Fim de curso
GPIO_PORT_IN_FDC_UPPER = 21
GPIO_PORT_IN_FDC_LOWER = 19

# Encoder
GPIO_PORT_IN_ENC_SIG1 = 11
GPIO_PORT_IN_ENC_SIG2 = 13

# Led
GPIO_PORT_OUT_LED = 16

# Servo
GPIO_PORT_OUT_PWM_SERVO = 12

# Buzzer
GPIO_PORT_OUT_BUZZER = 32

# Motor AGV
GPIO_PORT_OUT_AGV_SIG1 = 22
GPIO_PORT_OUT_AGV_SIG2 = 24
GPIO_PORT_OUT_AGV_EN = 26

# Vertical motor
GPIO_PORT_OUT_PARAF_SIG1 = 36
GPIO_PORT_OUT_PARAF_SIG2 = 38
GPIO_PORT_OUT_PARAF_EN = 40

# In and out GPIO ports
GPIO_PORTS_IN = [
    GPIO_PORT_IN_ULTR_ECHO,
    GPIO_PORT_IN_ENC_SIG1,
    GPIO_PORT_IN_ENC_SIG2,
    GPIO_PORT_IN_FDC_LOWER,
    GPIO_PORT_IN_FDC_UPPER,
]
GPIO_PORTS_OUT = [
    GPIO_PORT_OUT_ULTR_TRIGG,
    GPIO_PORT_OUT_LED,
    GPIO_PORT_OUT_PWM_SERVO,
    GPIO_PORT_OUT_AGV_SIG1,
    GPIO_PORT_OUT_AGV_SIG2,
    GPIO_PORT_OUT_AGV_EN,
    GPIO_PORT_OUT_BUZZER,
    GPIO_PORT_OUT_PARAF_SIG1,
    GPIO_PORT_OUT_PARAF_SIG2,
    GPIO_PORT_OUT_PARAF_EN,
]
